7.get/api/reviews/review id comment counter
mini-wizbit/Ash-s-Back-End-Portfolio pull request #8
Opened 2022-09-07 08:42 UTC by mini-wizbit

2022-09-07 09:01 UTC, mini-wizbit commented
Start on the 'add first test with happy path'

2022-09-07 09:07 UTC, emilyb93 commented on Model/review.model.js
> +            return reviewById;
I would prefer that this is done in SQL using the COUNT() aggregate function with a join. Saves us doing two queries everytime and SQL is very good at these operations. Have a look at the notes for SQL relationships 
https://notes.northcoders.com/courses/js-back-end/sql-relationships

2022-09-07 09:08 UTC, emilyb93 requested changes
Refactor into a single SQL query please, also dont add ALL of your files to a ticket. The patch and post files are not relevant to this ticket

2022-09-07 11:49 UTC, emilyb93 commented on Model/review.model.js
> +          });
I was more alluding to use doing this whole model with a single query, we can actually combine our query to select all the columns from the reviews table, and then ALSO use our COUNT() in the same query! 
When we use SELECT we can give that as many arguements as we want like

```SELECT reviews.review_id, reviews.votes, COUNT() AS comment_count etc ```

2022-09-07 11:50 UTC, emilyb93 requested changes
Would like to see this done as one query instead of 2

2022-09-08 11:17 UTC, pkaodev approved these changes
Nice one!  Merge away

2022-09-08 11:18 UTC, merged